### ISSUE TITLE
sizeForItem not called Help!!

### ISSUE THREAD

**Issue by davamp** [ngodacdu/SSSheetLayout#1]

**Comment by ngodacdu** [comment]
I checked, please set datasource for collection view
Guide: https://github.com/ngodacdu/SSSheetLayout#usage

**Comment by ngodacdu** [comment]
I checked, please set datasource for collection view
Guide: https://github.com/ngodacdu/SSSheetLayout#usage

**Comment by davamp** [comment]
But after I add data source just like you told me . It’s show an error
“'NSUnknownKeyException',
reason: '[<UIViewController 0x6e36ae0> setValue:forUndefinedKey:]: this
class is not key value coding-compliant for the key ”

**Comment by ngodacdu** [comment]
Can you provide informations of xcode version, device and iOS version?. I will try to reproduce

**Comment by davamp** [comment]
I built it in Xcode 9 with IOS 11

**Comment by ngodacdu** [comment]
I've used xcode 9.2 and built sample in iPhone 7, iOS 11.2 no matter what.
sizeForItem method called. I think that issue was generated from your project.
Look at the log, i think you should check xib or storyboard.

Ref 
https://stackoverflow.com/questions/3088059/what-does-this-mean-nsunknownkeyexception-reason-this-class-is-not-key-v

Please remove delegate outlet and reference outlet then connect outlet again.

If you still have that issue, please share code for me, i will support you.
Thank you.
